name: 🚀 Deploy via SSH Mahubiri backend

on:
  push:
    branches:
      - main # ou master selon ta branche

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧩 Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: 📦 Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: 🚀 Deploy to Hostinger via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./"
          target: ${{ secrets.DEPLOY_PATH }}
          rm: false
          overwrite: true
          strip_components: 0
      - name: 🔧 Run artisan commands remotely
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
